[package]
name = "queitite"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
colored = "3.0.0"
ordered-float = "5.1.0"
rand = "0.9.2"
rustc-hash = "2.1.1"
strum = { version = "0.27", features = ["derive"] }
